---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:1.32.0
        volumeMounts:
        - name: vaultwarden-volume
          mountPath: /data
        env:
        - name: SIGNUPS_ALLOWED
          value: {{ .Values.signups_allowed | quote }}
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 200Mi
        ports:
          - name: web
            containerPort: 80
            protocol: TCP
      volumes:
      - name: vaultwarden-volume
        persistentVolumeClaim:
          claimName: vaultwarden-pvc
