---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-internal-ing
  namespace: vaultwarden
spec:
  ingressClassName: nginx-internal
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: vaultwarden-tls-secret
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: vaultwarden-service
            port:
              number: 80
