---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: immich
  labels:
    app: immich
spec:
  replicas: 2
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:v1.127.0
          volumeMounts:
            - name: immich-media
              mountPath: /usr/src/app/upload
          env: 
            - name: DB_HOSTNAME
              value: immich-db-svc
            - name: DB_USERNAME
              value: immich
            - name: DB_PASSWORD
              value: immich
            - name: DB_DATABASE_NAME
              value: immich
            - name: REDIS_HOSTNAME
              value: immich-redis-svc
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machinelearning-svc:3003
          resources:
            requests:
              memory: 1Gi
          ports:
            - name: web
              containerPort: 2283
              protocol: TCP
      volumes:
        - name: immich-media
          persistentVolumeClaim:
            claimName: immich-media-pvc 


