---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx-internal
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: immich-tls-secret
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: immich-svc
            port:
              name: web
