---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: unifi-controller
  namespace: unifi-controller
  labels:
    app: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
        - name: unifi-controller
          image: linuxserver/unifi-controller:7.5.187
          volumeMounts:
            - name: unifi-controller-volume
              mountPath: /config
          resources:
            requests:
              memory: 1G
            limits:
              memory: 1G
          ports:
            - name: device-comm
              containerPort: 8080
              protocol: TCP
            - name: stun
              containerPort: 3478
              protocol: UDP
            - name: default-console
              containerPort: 8443
              protocol: TCP
            - name: secure-redirect
              containerPort: 8843
              protocol: TCP
            - name: http-redirect
              containerPort: 8880
              protocol: TCP
            - name: speedtest
              containerPort: 6789
              protocol: TCP
            - name: unifi-disc
              containerPort: 10001
              protocol: UDP
            - name: unifi-disc-l2
              containerPort: 1900
              protocol: UDP
      hostNetwork: {{ .Values.hostNetwork }}
      volumes:
        - name: unifi-controller-volume
          persistentVolumeClaim:
            claimName: unifi-controller-pvc
