---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-controller-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx-internal
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: unifi-controller-tls-secret
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: unifi-controller-tcp-svc
            port:
              name: default-console
