---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-controller-pvc
  namespace: unifi-controller
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
