---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-ngx-media-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
