---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ngx-ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
spec:
  ingressClassName: nginx-internal
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: paperless-ngx-tls-secret
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: paperless-ngx-svc
            port:
              name: web
