---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-internal-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/app-root: /admin/
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: pihole-tls-secret
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pihole-web-svc
                port:
                  name: web
