---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-config-pvc
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
