---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web-svc
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-svc
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancerIP }}
spec:
  type: LoadBalancer
  ports:
    - name: dns
      port: 53
  selector:
    app: pihole

