---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: unbound
  labels:
    app: unbound
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: crazymax/unbound:1.17.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: unbound-config-volume
              mountPath: /config/
              readOnly: true
          resources:
            requests:
              memory: 200Mi
            limits:
              memory: 200Mi
      volumes:
        - name: unbound-config-volume
          configMap:
            name: unbound-config
