---
apiVersion: v1
kind: Service
metadata:
  name: unbound-tcp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound-svc
spec:
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
  selector:
    app: unbound
---
apiVersion: v1
kind: Service
metadata:
  name: unbound-udp-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: unbound-svc
spec:
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  type: LoadBalancer
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    app: unbound
