---
apiVersion: v1
kind: Service
metadata:
  name: unbound
spec:
  type: LoadBalancer
  loadbalancerIP: 192.168.1.5
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 5335
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 5335
      protocol: UDP
  selector:
    app: unbound
  sessionAffinity: None
