---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.5
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 5335
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 5335
      protocol: UDP
  selector:
    app: unbound
