---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancerIP }}
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
    - name: dns-udp
      port: 53
  selector:
    app: unbound
