---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  strategy: 
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2025.6.2
          volumeMounts:
          - name: home-assistant-volume
            mountPath: /config
          - name: dockerenv # workaround for https://github.com/home-assistant/core/issues/133537
            mountPath: /.dockerenv            
          command: ["/bin/ash","-c","pip install pymysql && /init"]
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi
          ports:
            - name: web
              containerPort: 8123
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - NET_RAW
                - NET_BIND_SERVICE
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: home-assistant-volume
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: dockerenv
          emptyDir: {}
         
