---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-internal-ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx-internal
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: homeassistant-tls-secret
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: home-assistant-svc
            port:
              name: web
